# Site settings
name: Rishab Mallick
title: Rishab Mallick | Machine learning
description: CS undergrad focused on building machine learning solutions scalable on the real world
url: https://rishab.codes/
baseurl: ''
email: rishabmallick6@gmail.com
cover: https://rishab.codes/img/og.png
logo: https://rishab.codes/img/emojis/technologist.png
resume: https://rishab.codes/resume.pdf
social:
  - title: email
    url: mailto:rishabmallick6@gmail.com
  - title: twitter
    url: https://twitter.com/rishabtwi
  - title: github
    url: https://github.com/rishabgit
  - title: linkedin
    url: https://www.linkedin.com/in/rishabmallick

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
